function carInsuranceCompanies = carInsurance()
carInsuranceCompanies = {
    'State Farm';
    'GEICO';
    'Progressive';
    'Allstate';
    'Nationwide';
    'Farmers Insurance';
    'American Family Insurance';
    'Liberty Mutual Insurance';
    'Travelers Insurance';
    'Erie Insurance';
    'Auto-Owners Insurance';
    'The Hartford';
    'Safeco Insurance';
    'MetLife Auto & Home';
    'Amica Mutual Insurance';
    'AAA Auto Insurance';
    'Esurance';
    'USAA';
    'Country Financial';
    'Mercury Insurance';
    'Grange Insurance';
    'Kemper Auto';
    'Shelter Insurance';
    'Root Insurance';
    'Electric Insurance';
    'Hanover Insurance';
    'National General Insurance';
    'American National Insurance';
    'Acuity Insurance';
    'Westfield Insurance';
    'Cincinnati Insurance';
    'Pekin Insurance';
    'The General Insurance';
    'Safe Auto Insurance';
    'Acceptance Insurance';
    'Infinity Insurance';
    'Bristol West Insurance';
    'Unitrin Direct Auto Insurance';
    'MAPFRE Insurance';
    'The Hanover Insurance Group';
    'Ameriprise Auto & Home Insurance';
    'Victoria Insurance';
    'Direct Auto Insurance';
    'Response Insurance';
    'Elephant Insurance';
    'Encompass Insurance';
    'American Access Insurance';
    'Wawanesa Insurance';
    'Selective Insurance';
    'The Cincinnati Insurance Company';
    'Titan Insurance';
    'Permanent General Insurance';
    'Fred Loya Insurance';
    'National Interstate Insurance';
    };
end