function waterCompanies = list_water()
waterCompanies = {
    'American Water Works Company, Inc.';
    'California Water Service Group';
    'American States Water Company';
    'Aqua America, Inc.';
    'Middlesex Water Company';
    'Connecticut Water Service, Inc.';
    'SJW Group';
    'York Water Company';
    'American Water Resources';
    'California Water Association';
    'SouthWest Water Company';
    'American Water Corporate';
    'Utilities, Inc.';
    'H2O Innovation';
    'American Water Enterprises';
    'WaterOne';
    'American Water Resources Association';
    'Central States Water Resources';
    'Florida Water Resources Journal';
    'New Jersey Water Resources Association';
    'Colorado Water Resources Association';
    'Kansas Water Resources Association';
    'Georgia Water Resources Institute';
    'Illinois Water Resources Center';
    'Ohio Water Resources Center';
    'Texas Water Resources Institute';
    'Michigan Water Resources Association';
    'Water Resources Research Center';
    'North Carolina Water Resources Association';
    'Utah Water Research Laboratory';
    'Indiana Water Resources Association';
    'Minnesota Water Resources Conference';
    'Water Resources Management';
    'Tennessee Water Resources Research Center';
    'Kentucky Water Resources Research Institute';
    'Pennsylvania Water Resources Research Center';
    'Oklahoma Water Resources Center';
    'Water Resources Agency';
    'Virginia Water Resources Research Center';
    'Alabama Water Resources Research Institute';
    'New Mexico Water Resources Research Institute';
    'Wisconsin Water Resources Institute';
    'Water Resources Program';
    'Water Resources Research Laboratory';
    'Water Resources Research Institute';
    'Maryland Water Resources Research Center';
    'California Water Resources Center';
    'Missouri Water Resources Center';
    'Idaho Water Resources Research Institute';
    'Water Resources Department';
    'Water Resources Management Program';
    'Water Resources Management Association';
    'Water Resources Engineering';
    'Water Resources and Environment';
    'Water Resources Planning';
    'Water Resources Research Unit';
    'Water Resources Research Institute';
    'Water Resources Management and Policy';
    'Water Resources Systems';
    'Water Resources and Irrigation Engineering';
    'Water Resources Center';
    'Water Resources Engineering and Management';
    'Water Resources Science';
    'Water Resources Engineering and Technology';
    'Water Resources Systems Planning and Management';
    'Water Resources Systems Analysis';
    'Water Resources and Hydraulics';
    'Water Resources and Environmental Management';
    'Water Resources Systems Engineering';
    'Water Resources and Environmental Engineering';
    'Water Resources Planning and Management';
    'Water Resources Engineering and Development';
    'Water Resources Engineering and Planning';
    'Water Resources Management and Engineering';
    'Water Resources and Climate Change';
    'Water Resources and Environmental Sciences';
    'Water Resources Management and Policy Analysis';
    'Water Resources and Sustainability';
    'Water Resources and Aquatic Ecosystems';
    'Water Resources Engineering and Technology';
    'Water Resources and Coastal Engineering';
    'Water Resources and Hydrosystems';
    'Water Resources and Rural Development';
    'Water Resources and Agricultural Engineering';
    'Water Resources and Civil Engineering';
    'Water Resources and Earth Sciences';
    'Water Resources and Environmental Studies';
    'Water Resources and Environmental Management';
    'Water Resources and Hydrology';
    'Water Resources and Water Quality';
    'Water Resources and Climate Change';
    'Water Resources and Environmental Science';
    'Water Resources and River Engineering';
    'Water Resources and Rural Development';
    'Water Resources and Sustainable Development';
    'Water Resources and Environmental Management';
    'Water Resources and Water Management';
    };
end

