function utilityProviders = list_utilities()
utilityProviders = {
    'Pacific Gas and Electric Company (PG&E)';
    'Southern California Edison (SCE)';
    'San Diego Gas & Electric (SDG&E)';
    'Florida Power & Light (FPL)';
    'Duke Energy';
    'Dukeenergy'
    'Dominion Energy';
    'Con Edison (Consolidated Edison)';
    'National Grid';
    'Public Service Electric and Gas Company (PSE&G)';
    'American Electric Power (AEP)';
    'Xcel Energy';
    'Entergy Corporation';
    'Exelon Corporation';
    'NextEra Energy';
    'Georgia Power';
    'Alabama Power';
    'Mississippi Power';
    'Gulf Power';
    'Tampa Electric Company (TECO)';
    'Duke Energy Florida';
    'Progress Energy (now part of Duke Energy)';
    'Appalachian Power';
    'FirstEnergy Corp.';
    'PPL Corporation';
    'Baltimore Gas and Electric (BGE)';
    'Potomac Electric Power Company (Pepco)';
    'DTE Energy';
    'Consumers Energy';
    'CMS Energy';
    'Ameren Corporation';
    'ComEd (Commonwealth Edison)';
    'Nicor Gas';
    'Peoples Gas';
    'Northern Illinois Gas (North Shore Gas)';
    'Alliant Energy';
    'MidAmerican Energy';
    'Alliant Energy Interstate Power and Light (IPL)';
    'We Energies';
    'Wisconsin Public Service (WPS)';
    'Madison Gas and Electric (MGE)';
    'Xcel Energy - Northern States Power';
    'Minnesota Power';
    'Otter Tail Power Company';
    'Kansas City Power & Light (KCP&L)';
    'Evergy';
    'Westar Energy';
    'Omaha Public Power District (OPPD)';
    'Black Hills Energy';
    'Nebraska Public Power District (NPPD)';
    'Public Service Company of Oklahoma (PSO)';
    'Oklahoma Gas & Electric (OG&E)';
    'Public Service Company of New Mexico (PNM)';
    'El Paso Electric';
    'Arizona Public Service (APS)';
    'Salt River Project (SRP)';
    'Tucson Electric Power (TEP)';
    'NV Energy';
    'Idaho Power';
    'Rocky Mountain Power';
    'PacifiCorp';
    'Puget Sound Energy';
    'Seattle City Light';
    'Avista Utilities';
    'Portland General Electric (PGE)';
    'Pacific Power';
    'NorthWestern Energy';
    'Montana-Dakota Utilities Co.';
    'Black Hills Power';
    'Black Hills Colorado Electric';
    'Black Hills Wyoming Gas';
    'Black Hills Nebraska Gas';
    'Black Hills Energy Iowa Gas';
    'Black Hills Energy Arkansas Gas';
    'Black Hills Energy Kansas Gas';
    'Black Hills Energy Colorado Gas';
    'Black Hills Energy Nebraska Gas';
    'Black Hills Energy Wyoming Gas';
    'Black Hills Energy South Dakota Gas';
    'Black Hills Energy Iowa Gas';
    'Black Hills Energy Missouri Gas';
    'Black Hills Energy Montana Gas';
    'Black Hills Energy Kansas Gas';
    'Black Hills Energy Arkansas Gas';
    'Black Hills Energy Colorado Gas';
    'Black Hills Energy Nebraska Gas';
    'Black Hills Energy Wyoming Gas';
    'Black Hills Energy South Dakota Gas';
    'Black Hills Energy Iowa Gas';
    'Black Hills Energy Missouri Gas'
    'Black Hills Energy Montana Gas';
    'Black Hills Energy Kansas Gas';
    'Black Hills Energy Arkansas Gas';
    'Black Hills Energy Colorado Gas';
    };
end

