function schools = list_schools()
schools = {
    'Joliet Junior College';
    'Oakton Community College';
    'College of DuPage';
    'Harper College';
    'Moraine Valley Community College';
    'Elgin Community College';
    'William Rainey Harper College';
    'Triton College';
    'McHenry County College';
    'College of Lake County';
    'Kankakee Community College';
    'Rock Valley College';
    'Prairie State College';
    'Illinois Central College';
    'Heartland Community College';
    'John A. Logan College';
    'Lewis and Clark Community College';
    'Lincoln Land Community College';
    'Parkland College';
    'Black Hawk College';
    'Kishwaukee College';
    'Sauk Valley Community College';
    'Waubonsee Community College';
    'Shawnee Community College';
    'Spoon River College';
    'South Suburban College';
    'Lake Land College';
    'Richland Community College';
    'Illinois Valley Community College';
    'Rend Lake College';
    'Southeastern Illinois College';
    'Carl Sandburg College';
    'Danville Area Community College';
    'Lincoln Trail College';
    'Olney Central College';
    'Frontier Community College';
    'Wabash Valley College';
    'Sauk Valley Community College';
    'Black Hawk College';
    'Carl Sandburg College';
    'Spoon River College';
    'Illinois Central College';
    'Heartland Community College';
    'Lake Land College';
    'Lincoln Land Community College';
    'Parkland College';
    'Danville Area Community College';
    'John A. Logan College';
    'Kaskaskia College';
    'Kishwaukee College';
    'McHenry County College';
    'Moraine Valley Community College';
    'Morton College';
    'Oakton Community College';
    'Olivet Nazarene University';
    'Rend Lake College';
    'Richland Community College';
    'Sauk Valley Community College';
    'Shawnee Community College';
    'South Suburban College';
    'Southwestern Illinois College';
    'Spoon River College';
    'Triton College';
    'Waubonsee Community College';
    'Wabash Valley College';
    'Wilbur Wright College';
    'William Rainey Harper College';
    'Black Hawk College - East Campus';
    'Black Hawk College - Quad-Cities Campus';
    'Carl Sandburg College';
    'City Colleges of Chicago - Harold Washington College';
    'City Colleges of Chicago - Kennedy-King College';
    'City Colleges of Chicago - Malcolm X College';
    'City Colleges of Chicago - Olive-Harvey College';
    'City Colleges of Chicago - Richard J. Daley College';
    'City Colleges of Chicago - Truman College';
    'City Colleges of Chicago - Wilbur Wright College';
    'College of Lake County';
    'Danville Area Community College';
    'Elgin Community College';
    'Harper College';
    'Heartland Community College';
    'Highland Community College';
    'Illinois Central College';
    'Illinois Eastern Community Colleges - Frontier Community College';
    'Illinois Eastern Community Colleges - Lincoln Trail College';
    'Illinois Eastern Community Colleges - Olney Central College';
    'Illinois Eastern Community Colleges - Wabash Valley College';
    'Illinois Valley Community College';
    'John A. Logan College';
    'Joliet Junior College';
    'Kankakee Community College';
    'University of Chicago';
    'Northwestern University';
    'University of Illinois at Urbana-Champaign';
    'University of Michigan';
    'University of Wisconsin-Madison';
    'Purdue University';
    'University of Minnesota';
    'Ohio State University';
    'Michigan State University';
    'Indiana University Bloomington';
    'University of Iowa';
    'University of Notre Dame';
    'University of Cincinnati';
    'University of Kansas';
    'University of Missouri';
    'Iowa State University';
    'University of Nebraska-Lincoln';
    'University of Kentucky';
    'University of Dayton';
    'University of Illinois at Chicago';
    'University of Akron';
    'University of Toledo';
    'Marquette University';
    'Loyola University Chicago';
    'Ball State University';
    'Miami University';
    'Case Western Reserve University';
    'University of Louisville';
    'University of Wisconsin-Milwaukee';
    'Kansas State University';
    'University of Missouri-Kansas City';
    'University of Oklahoma';
    'University of Tulsa';
    'University of Northern Iowa';
    'University of South Dakota';
    'University of Kansas Medical Center';
    'University of Evansville';
    'University of Wisconsin-Whitewater';
    'University of Indianapolis';
    'DePaul University';
    'Saint Louis University';
    'University of Missouri-St. Louis';
    'Wichita State University';
    'Creighton University';
    'University of St. Thomas';
    'Bradley University';
    'University of Wisconsin-Stout';
    'University of Wisconsin-La Crosse';
    'Western Illinois University';
    'Eastern Illinois University';
    'University of Wisconsin-Parkside';
    'University of Wisconsin-Green Bay';
    'University of Wisconsin-Eau Claire';
    'University of Wisconsin-Oshkosh';
    'University of Wisconsin-Stevens Point';
    'University of Wisconsin-River Falls';
    'Northern Illinois University';
    'Southern Illinois University Carbondale';
    'Southern Illinois University Edwardsville';
    'Illinois State University';
    'Eastern Michigan University';
    'Central Michigan University';
    'Western Michigan University';
    'Oakland University';
    'Grand Valley State University';
    'Bowling Green State University';
    'Kent State University';
    'University of Toledo';
    'Cleveland State University';
    'Youngstown State University';
    'University of Akron';
    'University of Cincinnati';
    'Ohio University';
    'Xavier University';
    'University of Dayton';
    'University of Findlay';
    'University of Mount Union';
    'Ashland University';
    'Ohio Northern University';
    'Wright State University';
    'University of Detroit Mercy';
    'Wayne State University';
    'Michigan Technological University';
    'Central Missouri State University';
    'Truman State University';
    'University of Central Oklahoma';
    'University of Central Missouri';
    'Emporia State University';
    'Fort Hays State University';
    'Washburn University';
    'Missouri State University';
    'University of Missouri-Rolla';
    'Missouri Western State University';
    'Northwest Missouri State University';
    'Southwest Missouri State University';
    'University of Missouri-St. Louis';
    'University of Nebraska at Kearney';
    'University of Nebraska at Omaha';
    'University of Nebraska Medical Center';
    'University of Nebraska at Lincoln';
    'Creighton University';
    'University of South Dakota';
    'South Dakota State University';
    'North Dakota State University';
    'Harvard University';
    'Stanford University';
    'Massachusetts Institute of Technology (MIT)';
    'University of Cambridge';
    'University of Oxford';
    'California Institute of Technology (Caltech)';
    'Princeton University';
    'Yale University';
    'University of Chicago';
    'Columbia University';
    'University of Pennsylvania';
    'Cornell University';
    'University of California, Berkeley';
    'University of California, Los Angeles';
    'University of Michigan';
    'University of California, San Diego';
    'University College London (UCL)';
    'University of Toronto';
    'Johns Hopkins University';
    'Northwestern University';
    'University of California, San Francisco';
    'Swiss Federal Institute of Technology Zurich (ETH Zurich)';
    'University of Washington';
    'University of Wisconsin-Madison';
    'University of Texas at Austin';
    'University of Illinois at Urbana-Champaign';
    'Duke University';
    'University of California, Santa Barbara';
    'University of Melbourne';
    'University of Edinburgh';
    'New York University';
    'University of California, Davis';
    'University of British Columbia';
    'University of North Carolina at Chapel Hill';
    'University of Manchester';
    'University of Sydney';
    'University of Queensland';
    'University of New South Wales';
    'University of Bristol';
    'University of Hong Kong';
    'University of Amsterdam';
    'University of Copenhagen';
    'University of Zurich';
    'Peking University';
    'University of Tokyo';
    'National University of Singapore';
    'Australian National University';
    'University of Warwick';
    'Kings College London';
    'University of Southampton';
    'University of Glasgow';
    'University of Birmingham';
    'University of Nottingham';
    'University of Leeds';
    'University of Sheffield';
    'University of Southampton';
    'University of Auckland';
    'University of Alberta';
    'University of Waterloo';
    'University of Ottawa';
    'University of Western Ontario';
    'McGill University';
    'University of British Columbia';
    'University of Toronto';
    'University of Montreal';
    'University of Calgary';
    'University of Alberta';
    'University of Manitoba';
    'Queen''s University';
    'University of Saskatchewan';
    'Dalhousie University';
    'University of Ottawa';
    'University of Western Ontario';
    'University of Guelph';
    'Simon Fraser University';
    'University of Victoria';
    'York University';
    'Carleton University';
    'University of New Brunswick';
    'Memorial University of Newfoundland';
    'University of Windsor';
    'University of Manitoba';
    'Concordia University';
    'Laval University';
    'University of Quebec';
    'Ryerson University';
    'University of Regina';
    'McMaster University';
    'University of Calgary';
    'University of Saskatchewan';
    'University of Lethbridge';
    'University of Alberta';
    'University of Waterloo';
    'University of British Columbia';
    'University of Toronto';
    'University of Montreal';
    'University of Ottawa';
    'University of Western Ontario';
    'McGill University';
    'University of Alberta';
    'University of Calgary';
    'University of Manitoba';
    'University of Quebec';
    'University of Windsor';
    'Simon Fraser University';
    'Laval University';
    'University of Guelph';
    'University of Ottawa';
    'Concordia University';
    'York University';
    'University of Waterloo';
    'Purdue'
    'WCC'
    'MCC'
    'Waubonsee'
    'McHenry County College'
    'College'
    'University'
    'MATHTUTORDVD.COM'
    'TUTOR'
    'bookstore'
    'books'
    'School'
    'Phi'
    'Theta'
    'campus';

    };

end