function food = list_foods() 

food = {
    'VEND';  % Includes vending machines & kitchen
    'VENDING'  ;
    'Hot Box Pizza'
    'Pizza';
    'Burger';
    'Papa G''s'
    'Pasta';
    'Sushi';
    'Steak';
    'Tacos';
    'Salad';
    'Curry';
    'Sandwich';
    'Chicken Wings';
    'Soup';
    'Ramen';
    'Burrito';
    'DT Kirbys'
    'Fried Rice';
    'Pancakes';
    'Ice Cream';
    'Sushi Rolls';
    'Noodles';
    'Hot Dog';
    'Cupcake';
    'Smoothie';
    'CANTEEN';
    'Noodles & COMPANY';
    'COCA COLA';
    'COKE';
    'PEPSI';
    'CULVER';
    'Tropical Smoothi';
    'Tropical Smoothie';
    'Mannys Gelato';
    'Gelato';
    'SONIC';
    'HUNTLEY DAIRY';
    'Chick-fil-A';
    'Chipotle';
    'Popeyes';
    'McDonald''s';
    'McDonalds'
    'Buffalo Wild'
    'BWW'
    'Raising Canes'
    'Raising Cane''s'
    'Canes'
    'Triple X'
    'Burger King';
    'Rookies'
    'Pizza Hut';
    'Subway';
    'KFC';
    'Culvers'
    'Taco Bell';
    'Wendy''s';
    'Wendys'
    'Starbucks';
    'Panera Bread';
    'Dunkin'' Donuts';
    'Dunkin'
    'Dominos Pizza';
    'Domino''s'
    'Dominos'
    'Papa Johns';
    'Five Guys';
    'In-N-Out Burger';
    'Jamba Juice';
    'Panda Express';
    'Sonic Drive-In';
    'Arby''s';
    'Jack in the Box';
    'White Castle';
    'Dairy Queen';
    'Jimmy John''s';
    'Jimmy Johns'
    'Little Caesars';
    'Cinnabon';
    'Buffalo Wild Wings';
    'Chilis';
    'Red Lobster';
    'Olive Garden';
    'Outback Steakhouse';
    'Applebee''s';
    'IHOP';
    'Dennys';
    'Cracker Barrel';
    'Cheesecake Factory';
    'TGI Fridays';
    'Ruby Tuesday';
    'Texas Roadhouse';
    'Olive Garden';
    'LongHorn Steakhouse';
    'Golden Corral';
    'P.F. Chang''s';
    'Cheddar''s Scratch Kitchen';
    'Red Robin';
    'OCharleys';
    'Bob Evans';
    'Carrabba''s Italian Grill';
    'California Pizza Kitchen';
    'O''Charleys';
    'Famous Daves';
    'Papa Murphy''s';
    'Baskin-Robbins';
    'Cold Stone Creamery';
    'Orange Julius';
    'Noodles & Company';
    'Potbelly Sandwich Shop';
    'Cheesesteak Factory';
    'Sushi Shack';
    'Bistro 101';
    'Tandoori Times';
    'Peking Palace';
    'Pasta Paradiso';
    'BBQ Barn';
    'The Burger Joint';
    'Noodle House';
    'Taco Heaven';
    'Chicken Coop';
    'Crepes & Co.';
    'Fisherman''s Catch';
    'Vegetarian Delight';
    'Steak House';
    'Waffle World';
    'Salad Sensation';
    'Gourmet Grill';
    'Grubhub';
    'Uber Eats';
    'DoorDash';
    'Postmates';
    'Instacart';
    'Caviar';
    'Delivery.com';
    'Seamless';
    'Eat24';
    'Favor';
    'goPuff';
    'BeyondMenu';
    'ChowNow';
    'Slice';
    'Zomato';
    'Talabat';
    'Swiggy';
    'Foodpanda';
    'Deliveroo';
    'Just Eat';
    'Rappi';
    'Glovo';
    'SkipTheDishes';
    'Menufy';
    'Waitr';
    'EatStreet';
    'OrderUp';
    'Wrap City';
    'Soup & Sandwich';
    'Pizza Perfection';
    'Bakery Bliss';
    'Hot Pot Haven';
    'Burger Bliss';
    'Mexican Fiesta';
    'Seafood Paradise';
    'Deli Delight';
    'Ramen House';
    'Pancake Palace';
    'Italiano Express';
    'Mediterranean Magic';
    'Fried Chicken Fiesta';
    'Sizzling Sizzlers';
    'Candy Land';
    'Smoothie Sensation';
    'Street Taco Stop';
    'Nacho Nation';
    'Sushi Supreme';
    'Burrito Bonanza';
    'Pita Paradise';
    'Bagel Boutique';
    'Curry Corner';
    'Brewery Bites';
    'Bowl of Pho';
    'Greek Grill';
    'Dessert Delights';
    'Tasty Thai';
    'Dim Sum Delight';
    'Hawaiian Hideaway';
    'French Bakery';
    'Korean BBQ';
    'Mongolian Grill';
    'Falafel House';
    'Cajun Cookout';
    'Gourmet Gelato';
    'Peruvian Flavors';
    'Cuban Cuisine';
    'Boba Tea Bar';
    'Starbucks';
    'Dunkin'' Donuts';
    'Tim Hortons';
    'Peet''s Coffee';
    'Caribou Coffee';
    'The Coffee Bean & Tea Leaf';
    'Seattle''s Best Coffee';
    'Panera Bread';
    'Coldstone'
    'Wolfies'
    'Grill'
    'McDonald''s McCafé';
    'Café Nero';
    'Costa Coffee';
    'Gloria Jean''s Coffees';
    'Caffè Bene';
    'Second Cup';
    'PJ''s Coffee';
    'Dunn Brothers Coffee';
    'Biggby Coffee';
    'It''s a Grind Coffee House';
    'Dutch Bros Coffee';
    'Scooter''s Coffee';
    'Café Grumpy';
    'La Colombe Coffee Roasters';
    'Intelligentsia Coffee';
    'Blue Bottle Coffee';
    'Stumptown Coffee Roasters';
    'Peetniks';
    'Philz Coffee';
    'Bulletproof Coffee';
    'Black Rifle Coffee Company';
    'Revv';
    'Krispy Kreme Coffee';
    'Lavazza';
    'Julius Meinl';
    'Tully''s Coffee';
    'Caffe Ladro';
    'Bluestone Lane';
    'Folgers Coffee';
    'Maxwell House Coffee';
    'Illy';
    'Keurig';
    'Nespresso';
    'Eight O''Clock Coffee';
    'Community Coffee';
    'Lavazza';
    'Kicking Horse Coffee';
    'Peet''s Coffee';
    'Gevalia';
    'Starbucks Reserve';
    'PJ''s Coffee';
    'Death Wish Coffee';
    'Koffee Kult';
    'Bulletproof Coffee';
    'Boca Java';
    'San Francisco Bay Coffee';
    'Lavazza';
    'Loyalty Coffee';
    'Stumptown Coffee Roasters';
    'Caffe Vita';
    'Black Rifle Coffee Company';
    'Ceremony Coffee Roasters';
    'Verve Coffee Roasters';
    'Equator Coffees';
    'Madcap Coffee';
    'Porillos'
    'Heart Coffee Roasters';
    'Onyx Coffee Lab';
    'Campos Coffee';
    'Proud Mary Coffee';
    'Boxcar Coffee Roasters';
    'Parlor Coffee';
    'Sightglass Coffee';
    'Intelligentsia Coffee';
    'Four Barrel Coffee';
    'Counter Culture Coffee';
    'ReAnimator Coffee';
    'Sump Coffee';
    'Cat & Cloud Coffee';
    'Craft & Mason Roasting Co.';
    'Blueprint Coffee';
    'Methodical Coffee';
    'Sweet Bloom Coffee Roasters';
    'George Howell Coffee';
    'Ritual Coffee Roasters';
    'Augie''s Coffee Roasters';
    'Madcap Coffee';
    'Heart Coffee Roasters';
    'Sump Coffee';
    'Cat & Cloud Coffee';
    'Craft & Mason Roasting Co.';
    'Blueprint Coffee';
    'Methodical Coffee';
    'Sweet Bloom Coffee Roasters';
    'George Howell Coffee';
    'Ritual Coffee Roasters';
    'Augie''s Coffee Roasters';
    'Revelator Coffee Company';
    'Colectivo Coffee';
    'Crema Coffee';
    'Dark Matter Coffee';
    'Cartel Coffee Lab';
    'Ultimo Coffee';
    'Joe Coffee Company';
    'Dogwood Coffee Co.';
    'Olympia Coffee';
    'Onyx Coffee Lab';
    'Cafe Salsa';
    'Alexander''s Cafe';
    'Port Edward Restaurant';
    'D''Andrea Banquets & Conference Center';
    'The Cottage';
    'Biaggi''s Ristorante Italiano';
    'Pinstripes';
    'Parkside Pub';
    'Avante Banquets & Conference Center';
    'Jameson''s Charhouse';
    'Duke''s Alehouse and Kitchen';
    'The Chop House';
    'Gianni''s Cafe';
    'Cooper''s Hawk Winery & Restaurant';
    'Bistro Wasabi';
    'The Lucky Monk';
    'Francesca''s by the River';
    'Waverly Inn';
    'Maggiano''s Little Italy';
    'Morton''s The Steakhouse';
    'Dover Straits';
    'Shakou Barrington';
    'Tokio Sake';
    'Szechwan Palace';
    'Eddie Merlot''s Prime Aged Beef & Seafood';
    'Wildfire';
    'Penny Road Pub';
    'Cucina Bella';
    'Copper Fiddle Distillery';
    'Bonefish Grill';
    'Toro Sushi';
    'Jameson''s Original Charhouse';
    'Emmett''s Brewing Company';
    'D''Agostino''s Pizzeria';
    'Brickstone Brewery';
    'Kuma''s Corner';
    'Bahama Breeze';
    };
