function cars = list_cars()
cars = {
    'Ford';
    'General Motors';
    'Chevrolet';
    'Buick';
    'GMC';
    'Cadillac';
    'Chrysler';
    'Dodge';
    'Jeep';
    'Ram';
    'Lincoln';
    'Tesla';
    'Toyota';
    'Honda';
    'Nissan';
    'Mazda';
    'Subaru';
    'Kia';
    'Hyundai';
    'Volkswagen';
    'Audi';
    'BMW';
    'Mercedes-Benz';
    'Volvo';
    'Lexus';
    'Acura';
    'Infiniti';
    'Land Rover';
    'Jaguar';
    'Porsche';
    'Mini';
    'Fiat';
    'Alfa Romeo';
    'Maserati';
    'Bentley';
    'Rolls-Royce';
    'McLaren';
    'Aston Martin';
    'Ferrari';
    'Lamborghini';
    'Bugatti';
    'Genesis';
    'Honda of America';
    'Toyota Motor Manufacturing';
    'Ford Motor Company';
    'General Motors';
    'Chrysler';
    'Subaru of Indiana Automotive';
    'Honda Manufacturing of Indiana';
    'Toyota Motor Manufacturing';
    'Ford Kansas City Assembly Plant';
    'General Motors';
    'Chrysler';
    'Toyota Motor Manufacturing';
    'Honda Manufacturing';
    'Subaru of Indiana Automotive';
    'Ford Motor Company';
    'General Motors';
    'Chrysler';
    'Toyota Motor Manufacturing';
    'Honda Manufacturing of Indiana';
    'Subaru of Indiana Automotive';
    'Tesla Motors';
    'BMW Manufacturing';
    'Mercedes-Benz U.S. International';
    'Volkswagen Group of America';
    'Hyundai Motor Manufacturing';
    'Kia Motors Manufacturing';
    'Nissan North America';
    'CARMAX';
    'DriveTime';
    'AutoNation';
    'Carvana';
    'Vroom';
    'Shift';
    'EchoPark Automotive';
    'HGreg.com';
    'Off Lease Only';
    'Texas Direct Auto';
    'Enterprise Car Sales';
    'Penske Automotive Group';
    'Sonic Automotive';
    'Lithia Motors';
    'Group 1 Automotive';
    'Asbury Automotive Group';
    'AutoLenders';
    'OffLeaseOnly.com';
    'Napleton Auto Group';
    'Ferman Automotive Group';
    'Fitzgerald Auto Mall';
    'Tom Wood Automotive Group';
    'Hendrick Automotive Group';
    'Pohanka Automotive Group';
    'Luther Automotive Group';
    'Holman Automotive Group';
    'Jeff Wyler Automotive Family';
    'Larry H. Miller Dealerships';
    'Findlay Auto Group';
    'Bommarito Automotive Group';
    'Sheehy Auto Stores';
    'Ken Garff Automotive Group';
    'Dave Smith Motors';
    'Morrie''s Automotive Group';
    'Anderson Automotive Group';
    'Ed Napleton Automotive Group';
    'Germain Automotive Group';
    'Leith Automotive Group';
    'AutoFair Automotive Group';
    'Fletcher Jones Automotive Group';
    'Hiley Automotive Group';
    'Bachman Auto Group';
    'Rick Hendrick Automotive Group';
    'Ganley Automotive Group';
    'Courtesy Automotive Group';
    'Sullivan Automotive Group';
    'Priority Automotive Group';
    'Jeff Schmitt Auto Group';
    'West Herr Automotive Group';
    'Serra Automotive Group';
    'Fette Auto Group';
    'Keyes Automotive Group';
    'Grossinger Auto Group';
    'Nyle Maxwell Auto Group';
    'Goodyear Auto Service';
    'Firestone Complete Auto Care';
    'Meineke Car Care Center';
    'Jiffy Lube';
    'Midas';
    'Tuffy Tire & Auto Service';
    'Monro Auto Service and Tire Centers';
    'AAMCO Transmissions & Total Car Care';
    'Precision Tune Auto Care';
    'Mr. Tire Auto Service Centers';
    'Tire Discounters';
    'Valvoline Instant Oil Change';
    'SpeeDee Oil Change & Auto Service';
    'Brakes Plus';
    'Grease Monkey';
    'Big O Tires';
    'Take 5 Oil Change';
    'Milex Complete Auto Care';
    'Tire Kingdom';
    'Express Oil Change & Tire Engineers';
    'Tire Pros';
    'Car-X Tire & Auto';

    };
end

